name: Import secrets and variables to Depot CI
on: push

permissions:
  id-token: write
  contents: read

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: depot/setup-action@v1
      - name: Import secrets
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        run: |
          unset DEPOT_TOKEN
          depot ci secrets add TAURI_SIGNING_PRIVATE_KEY="$TAURI_SIGNING_PRIVATE_KEY" TAURI_SIGNING_PRIVATE_KEY_PASSWORD="$TAURI_SIGNING_PRIVATE_KEY_PASSWORD" --repo vyeos/GEWT
